{% set name = "PyWaffle" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: ac2deba1db4775d7b6381e8d75416dfda1e7286f3cf1436bad50fc0616ac2996

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base

test:
  imports:
    - pywaffle

about:
  home: https://github.com/ligyxy/PyWaffle
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A FigureClass of Matplotlib to make waffle chart.

  description: |
    PyWaffle is a Python package to make waffle chart, bases on Matplotlib.
    It provides a Figure constructor class Waffle, which could be passed to 
    matplotlib.pyplot.figure and generates a matplotlib Figure object.
  doc_url: https://pywaffle.readthedocs.io/en/latest/
  dev_url: https://github.com/ligyxy/PyWaffle

extra:
  recipe-maintainers:
    - philip-khor
