{% set name = "PyWaffle" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: e32f5a5f50899547d0f6bc2dcb97cb0afe2651e15f8df941b06d5bb02988e933
  
build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:

  host:
    - python >=3
    - pip
  run:
    - python >=3
    - matplotlib

test:
  imports:
    - pywaffle

about:
  home: https://github.com/ligyxy/PyWaffle
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A FigureClass of Matplotlib to make waffle chart.'

  description: |
    PyWaffle is a Python package to make waffle chart, bases on Matplotlib.
    It provides a Figure constructor class Waffle, which could be passed to 
    matplotlib.pyplot.figure and generates a matplotlib Figure object.
  doc_url: https://pywaffle.readthedocs.io/en/latest/
  dev_url: https://github.com/ligyxy/PyWaffle

extra:
  recipe-maintainers:
    - philip-khor
